---
title: "Przykłady wykresów"
header-includes:
  - \usepackage[polish]{babel}
output:
  html_document:
    toc: true
    toc_depth: 5
    toc_float:
      collapsed: false
      smooth_scroll: false
  pdf_document:
    toc: yes
    toc_depth: '5'
---
<style type="text/css">
.title {
  display: none;
}

.table {
    width:70%;
}

#getting-started img {
  margin-right: 10px;
}

</style>

[Wersja pdf](przyklady.pdf)

# Przykłady wykresów

## Przykład 1

Komentarz: pierwszy parametr `axis` określa położenie osi: 1- dół, 2- lewa strona, 3 - góra, 4 - prawa strona.

```{r}
a<-c(1,2,3,4,5,6,7)
b<-c(23,3,2,4,5,2,-2)
plot(a,b,axes=FALSE,type="o",col="blue",ann=FALSE)
axis(4, las=1, at=10*0:range(b)[2])
axis(3, at=1:7, lab=c("Pn","Wt","Śr","Czw","Pt","So","Nd"))
box()
```



## Przykład 2

Jeśli w parametrze `at` chcemy mieć kontrolę nad tym co będzie, możemy dodać tam ręcznie konkretny wektor.
```{r}
a<-c(1,2,3,4,5,6,7)
b<-c(23,3,2,4,5,2,-2)
plot(a,b,axes=FALSE,type="o",col="blue",ann=FALSE)
axis(2, las=1, at=c(0,5,17,20,23))
axis(1, at=1:7, lab=c("Pn","Wt","Śr","Czw","Pt","So","Nd"))
box()
```

</div>

